[package]
name        = "rover-bus"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
rover-msgs = { workspace = true }
rover-link = { workspace = true }
serde      = { version = "1", features = ["derive"] }
toml       = "1"
